apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 100-master-kernel-arg-disable-efi-framebuffer
spec:
  config:
    ignition:
      version: 3.4.0
  kernelArguments:
    - video=efifb:off
