# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

FROM ghcr.io/t-c-l-o-u-d/devcontainer-base-images/fedora-devcontainer:latest

# pull in USER from devcontainer.json
ARG USER

# add bash files
COPY files/config-openshift-devcontainer /etc/skel/.config/bash/

# add the USER to the image
RUN useradd --create-home --shell /usr/bin/bash --groups wheel ${USER}

# =======================================
# repository specific commands start here
# =======================================

RUN dnf5 install --assumeyes \
    butane \
    golang \
    httpd-tools \
    jq \
    yamllint \
    yq

# copy oc binary
COPY files/oc /usr/local/bin/oc

# copy kubectl binary
COPY files/oc /usr/local/bin/kubectl

# # trust OpenShift cert
# COPY files/api-vulcan-internal.crt /etc/pki/ca-trust/source/anchors/

# # trust Registry cert
# COPY files/default-route-openshift-image-registry.apps.vulcan.internal.crt /etc/pki/ca-trust/source/anchors/

# RUN update-ca-trust

# =====================================
# repository specific commands end here
# =====================================

# ensure the image starts as USER
USER ${USER}
